package com.teamcaffeine.koja.constants

object EnvironmentVariableConstant {
    const val KOJA_AWS_RDS_DATABASE_URL = "KOJA_AWS_RDS_DATABASE_URL"
    const val KOJA_AWS_RDS_DATABASE_ADMIN_USERNAME = "KOJA_AWS_RDS_DATABASE_ADMIN_USERNAME"
    const val KOJA_AWS_RDS_DATABASE_ADMIN_PASSWORD = "KOJA_AWS_RDS_DATABASE_ADMIN_PASSWORD"
    const val KOJA_AWS_DYNAMODB_ACCESS_KEY_ID = "KOJA_AWS_DYNAMODB_ACCESS_KEY_ID"
    const val KOJA_AWS_DYNAMODB_ACCESS_KEY_SECRET = "KOJA_AWS_DYNAMODB_ACCESS_KEY_SECRET"
    const val GOOGLE_CLIENT_ID = "GOOGLE_CLIENT_ID"
    const val GOOGLE_CLIENT_SECRET = "GOOGLE_CLIENT_SECRET"
    const val GOOGLE_MAPS_API_KEY = "GOOGLE_MAPS_API_KEY"
    const val KOJA_JWT_SECRET = "KOJA_JWT_SECRET"
    const val OPENAI_API_KEY = "OPENAI_API_KEY"
    const val KOJA_ID_SECRET = "KOJA_ID_SECRET"
    const val COVERALLS_REPO_TOKEN = "COVERALLS_REPO_TOKEN"
    const val KOJA_PRIVATE_KEY_PASS = "KOJA_PRIVATE_KEY_PASS"
    const val KOJA_PRIVATE_KEY_SALT = "KOJA_PRIVATE_KEY_SALT"
    const val AI_PRIVATE_KEY_PASS = "AI_PRIVATE_KEY_PASS"
    const val AI_PRIVATE_KEY_SALT = "AI_PRIVATE_KEY_SALT"
    const val SERVER_ADDRESS = "SERVER_ADDRESS"
    const val SERVER_PORT = "SERVER_PORT"
}
