name: Koja CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - dev

jobs:
  build_and_test_flutter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create .env
        run: |
          echo KOJA_AWS_RDS_DATABASE_URL=${{ secrets.KOJA_AWS_RDS_DATABASE_URL }} >> .env
          echo KOJA_AWS_RDS_DATABASE_ADMIN_USERNAME=${{ secrets.KOJA_AWS_RDS_DATABASE_ADMIN_USERNAME }} >> .env
          echo KOJA_AWS_RDS_DATABASE_ADMIN_PASSWORD=${{ secrets.KOJA_AWS_RDS_DATABASE_ADMIN_PASSWORD }} >> .env
          echo GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} >> .env
          echo GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} >> .env
          echo KOJA_JWT_SECRET=${{ secrets.KOJA_JWT_SECRET }} >> .env
          echo COVERALLS_REPO_TOKEN=${{ secrets.COVERALLS_REPO_TOKEN }} >> .env
          echo API_KEY=${{ secrets.API_KEY }} >> .env

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.10'
          
      - name: Install Flutter dependencies
        run: flutter pub get
        working-directory: client
        
      - name: Run Flutter linter
        run: flutter analyze
        working-directory: client

      - name: Run Flutter Tests
        run: flutter test
        working-directory: client

      - name: Build Flutter app
        run: flutter build apk
        working-directory: client

  build_and_test_springboot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17
          
      - name: Run Linter
        run: ./gradlew ktlintCheck
      
      - name: Build Spring Boot project
        run: ./gradlew build

      - name: Run Tests
        run: ./gradlew test
