name: Koja CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test_flutter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.10'

      - name: Install Flutter dependencies
        run: flutter pub get
        working-directory: src/client

      - name: Run Flutter tests
        run: flutter test
        working-directory: src/client

      - name: Build Flutter app
        run: flutter build apk
        working-directory: src/client

  build_and_test_springboot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List directory contents
        run: ls -la

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build and test Spring Boot project
        run: ./gradlew build test
